# Generated by Django 4.0.2 on 2022-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superhero', models.CharField(max_length=200)),
                ('publisher', models.TextField()),
                ('alter_ego', models.TextField()),
                ('first_appearance', models.TextField()),
                ('characters', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
